Ensure isVisible returns a Boolean
jupyterlab-contrib/jupyterlab-favorites pull request #11
Opened 2022-12-26 06:42 UTC by mctoohey

`this._showWidget` can be undefined when the plugin is initially loading. This can cause the widget to never render because React 17 and below will error if `undefined` is returned in the render function.

I think this has always been a race condition but was very rare. However, since Jupyterlab `v4.0.0a27` I have found that this issue happens consistently and the Favorites never renders widget.

2023-01-02 11:46 UTC, mctoohey commented
@fcollonval When you have some spare time, would you be able to give this a review?

2023-01-02 13:43 UTC, fcollonval requested changes

2023-01-02 13:43 UTC, fcollonval commented on src/manager.ts
> +    return Boolean(this._showWidget && this.visibleFavorites().length > 0);
Thanks @mctoohey would you mind changing the fix to set `this._showWidget = true;` in the constructor of `FavoritesManager`? That will be more robust.

2023-01-03 02:07 UTC, mctoohey commented
Thanks, I've updated the original commit to initialise `this._showWidget = true;`

2023-01-03 08:19 UTC, fcollonval approved these changes
Thanks @mctoohey

2023-01-03 08:26 UTC, merged